/* Shared interaction affordances. Source editing remains owned by app.js. */
(() => {
  const A=Inkblots,I=InkblotsI18n,$=s=>document.querySelector(s);
  const label=(e,text,attr)=>I.bind(e,text,attr);
  function button(text,description,fn){const b=document.createElement('button');b.className='btn';label(b,text);label(b,description,'title');label(b,description,'aria-label');b.onclick=fn;return b;}
  const split=document.createElement('div');split.className='inspector-split';split.tabIndex=0;split.setAttribute('role','separator');split.setAttribute('aria-orientation','horizontal');label(split,'Resize script and global variables','aria-label');$('#global-manager').before(split);
  let ratio=Number(localStorage.getItem('inkblots-inspector-split'))||.5;
  function size(value){ratio=Math.max(.2,Math.min(.8,value));$('#side-body').style.flex=`0 0 calc(${ratio*100}% - 4px)`;$('#global-manager').style.flex='1 1 0';split.setAttribute('aria-valuenow',Math.round(ratio*100));split.setAttribute('aria-valuemin','20');split.setAttribute('aria-valuemax','80');localStorage.setItem('inkblots-inspector-split',ratio);}
  split.onpointerdown=e=>{split.setPointerCapture(e.pointerId);e.preventDefault();};split.onpointermove=e=>{if(split.hasPointerCapture(e.pointerId)){const r=$('#side').getBoundingClientRect();size((e.clientY-r.top)/r.height);}};split.onpointerup=e=>{if(split.hasPointerCapture(e.pointerId))split.releasePointerCapture(e.pointerId);};split.ondblclick=()=>size(.5);split.onkeydown=e=>{if(['ArrowUp','ArrowDown','Home'].includes(e.key)){e.preventDefault();size(e.key==='Home'?.5:ratio+(e.key==='ArrowUp'?-.05:.05));}};size(ratio);
  const results=document.createElement('span');results.id='search-results';results.setAttribute('role','status');const previous=button('↑','Previous match',()=>move(-1)),next=button('↓','Next match',()=>move(1));$('#search').after(results,previous,next);let hits=[],index=-1;
  function update(){const q=$('#search').value.trim().toLowerCase();hits=q?A.State.order.filter(id=>id.toLowerCase().includes(q)||A.State.nodes[id].body.toLowerCase().includes(q)):[];index=-1;results.textContent=q?(hits.length?I.t('{count} matches',{count:hits.length}):I.t('No matches')):'';previous.hidden=next.hidden=!q;previous.disabled=next.disabled=!hits.length;}
  function move(delta){if(!hits.length)return;index=index<0?(delta>0?0:hits.length-1):(index+delta+hits.length)%hits.length;A.select(hits[index]);A.centerOn(hits[index]);results.textContent=`${index+1} / ${hits.length}`;$('#search').focus();}
  $('#search').addEventListener('input',update);$('#search').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();move(e.shiftKey?-1:1);}});window.addEventListener('inkblots-render',update);window.addEventListener('inkblots-language',update);update();
  const closes={'#b-playclose':'Close play','#b-errclose':'Close problems','#b-srcclose':'Close Full script'};for(const [selector,text]of Object.entries(closes)){label($(selector),text,'title');label($(selector),text,'aria-label');}
  $('#toast').setAttribute('role','status');$('#toast').setAttribute('aria-live','polite');
  const test=document.createElement('dialog');test.className='help-guide';test.id='test-state-dialog';test.addEventListener('keydown',e=>e.stopPropagation());document.body.append(test);
  window.InkblotsTest={open(id,run){test.textContent='';const header=document.createElement('header'),title=document.createElement('h2');label(title,'Test from here');header.append(title,button('Close','Close',()=>test.close()));const description=document.createElement('p');label(description,'Starts with fresh state; earlier choices and effects are not replayed.');test.append(header,description);const fields=[];
    for(const v of InkblotsGlobals.declarations().filter(v=>v.kind==='VAR')){let value;try{value=JSON.parse(v.value);}catch{continue;}if(!['string','boolean','number'].includes(typeof value))continue;const row=document.createElement('label');row.className='test-variable';const name=document.createElement('span');name.textContent=v.name;const input=document.createElement('input');input.value=typeof value==='string'?value:String(value);input.type=typeof value==='number'?'number':'text';if(typeof value==='boolean')input.setAttribute('list','ink-value-suggestions');row.append(name,input);test.append(row);fields.push({name:v.name,input,value});}
    const error=document.createElement('p');error.className='field-error';error.setAttribute('role','status');test.append(error,button('Play','Play',()=>{const values={};for(const field of fields){let value=field.input.value;if(typeof field.value==='boolean'){if(!['true','false'].includes(value)){label(error,'Use true or false for boolean test values.');return;}value=value==='true';}else if(typeof field.value==='number'){value=Number(value);if(!field.input.value.trim()||!Number.isFinite(value)){label(error,'Enter a number for numeric test values.');return;}}if(value!==field.value)values[field.name]=value;}test.close();run(values);}));test.showModal();}};
  $('#canvas').addEventListener('mouseover',e=>{const text=e.target.closest('[contenteditable]')?'Edit story text · Enter to finish · Escape to cancel':e.target.closest('.pill[data-idx],.choice-port[data-idx],.addout')?'Drag a connection to another knot':e.target.closest('.condition-tag,.variable-change')?'Story information · edit in the inspector':'Shift-drag to select · Ctrl+G to group';label($('#st-hint'),text);});
  window.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='a'&&!e.target.closest?.('input,textarea,[contenteditable],dialog,.modal')&&A.Tabs.length){e.preventDefault();InkblotsCanvas.selectMany(A.State.order.filter(id=>A.State.nodes[id]._el));}});
})();
