const path=require('node:path'),fs=require('node:fs'),os=require('node:os');
if(!process.versions.electron){const env={...process.env};delete env.ELECTRON_RUN_AS_NODE;const result=require('node:child_process').spawnSync(require('electron'),[__filename],{env,stdio:'inherit',timeout:90000});if(result.error)throw result.error;process.exit(result.status??1);}
const {app,BrowserWindow,ipcMain}=require('electron');
const output=process.env.INKBLOTS_QA_DIR||fs.mkdtempSync(path.join(os.tmpdir(),'inkblots-design-'));
app.setPath('userData',fs.mkdtempSync(path.join(os.tmpdir(),'inkblots-design-profile-')));
ipcMain.on('system-languages',e=>e.returnValue=['en-US']);
async function checks(){
  const A=Inkblots,G=InkblotsGlobals,C=InkblotsCanvas,$=s=>document.querySelector(s),check=(value,message)=>{if(!value)throw Error(message);console.log('PASS '+message);},wait=()=>new Promise(r=>setTimeout(r,100));
  const fixture='VAR score = 0\nVAR ready = false\nCONST limit = 3\nLIST badges = red, blue\n-> scene\n=== scene ===\nAt the door.\n* You [enter] step inside.\n    A warm room.\n    ~ score += 1\n    ** [Look]\n        Books everywhere.\n    ** [Listen]\n        A clock ticks.\n    -- The room is quiet.\n* [Wait]\n    ~ score += 2\n    Cold outside.\n- Back together.\n+ [Leave] -> ending\n+ {ready} [Stay] -> ending\n=== ending ===\nThe end.\n-> END';
  A.load(fixture);await wait();A.select('scene');const card=()=>A.State.nodes.scene._el;
  check(A.compile().story,'Nested weave fixture compiles');
  check(!card().querySelector('.prose .variable-change'),'Branch effects are not represented as node-entry effects');
  const first=card().querySelector('.choice-row'),response=first.querySelector('.choice-response');
  check(response.textContent.includes('A warm room.')&&response.textContent.includes('score += 1'),'Branch response and effect belong to their choice');
  check(response.querySelectorAll('.choice-row').length===2,'Nested choices are contained in their parent branch');
  check(response.textContent.includes('The room is quiet.')&&!response.textContent.includes('Cold outside.'),'Nested rejoin stays inside its branch');
  const shared=card().querySelector('.story-flow > .choice-continuation');check(shared.textContent.includes('Back together.'),'Shared gather is a separate continuation');
  check(card().querySelectorAll('.story-flow > .flow-heading').length===2,'Successive choice groups have separate headings');
  const inline=response.querySelector('.story-line .story-text');inline.focus();inline.textContent=' walk inside.';inline.dispatchEvent(new Event('input'));inline.blur();check(A.State.nodes.scene.body.includes('* You [enter] walk inside.'),'Output-only response text edits without exposing syntax');A.undo();
  const value=$('[data-name="score"] .global-value');value.focus();value.value='99';value.dispatchEvent(new Event('input'));value.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}));await wait();check(G.declarations().find(v=>v.name==='score').value==='0','Escape cancels a global value edit');
  const name=$('[data-name="score"] .global-name');name.value='ready';name.dispatchEvent(new Event('change'));check(name.getAttribute('aria-invalid')==='true'&&name.parentElement.querySelector('.field-error').textContent.includes('already'),'Duplicate name validation is attached to its field');name.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}));
  $('[data-name="score"] button').click();check($('#scrim').classList.contains('open')&&$('#m-desc').textContent.includes('other lines'),'Deleting a referenced declaration asks with reference warning');$('#m-cancel').click();check(G.declarations().some(v=>v.name==='score'),'Cancel keeps the declaration');
  $('[data-name="score"] button').click();$('#m-ok').click();check(!G.declarations().some(v=>v.name==='score')&&$('#toast').textContent.includes('undo'),'Deletion has undo feedback');A.undo();
  const category=$('.global-category');category.value='CONST';category.dispatchEvent(new Event('change'));check($('[data-name="limit"]'),'Constants have their own section');category.value='LIST';category.dispatchEvent(new Event('change'));check($('[data-name="badges"] .global-value').title.includes('Comma-separated'),'Lists have syntax guidance');category.value='VAR';category.dispatchEvent(new Event('change'));
  const splitter=$('.inspector-split'),initial=$('#side-body').getBoundingClientRect().height;splitter.dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowDown',bubbles:true}));check($('#side-body').getBoundingClientRect().height>initial,'Inspector split is keyboard resizable');splitter.dispatchEvent(new KeyboardEvent('keydown',{key:'Home',bubbles:true}));
  $('#b-source').click();const draft=$('#srctext').value+'\n// retained draft';$('#srctext').value=draft;$('#srctext').dispatchEvent(new Event('input'));$('#b-srcclose').click();$('#b-source').click();check($('#srctext').value===draft,'Closing Full script preserves its draft');$('#b-srcclose').click();const previous=A.activeTab;A.newFile();A.switchTab(previous);$('#b-source').click();check($('#srctext').value===draft,'Draft is retained independently across tabs');$('#b-srcclose').click();
  A.setDirty(false);const pending=A.confirmWindowClose();check($('#scrim').classList.contains('open'),'Unapplied draft alone protects window close');$('#m-cancel').click();check(await pending===false,'Draft close cancellation preserves the session');$('#b-source').click();$('#b-srcapply').click();check(A.State.sourceDraft==null&&A.serialize(false).text.includes('retained draft'),'Applying draft updates source and clears pending draft');
  const search=$('#search');search.value='door';search.dispatchEvent(new Event('input'));check($('#search-results').textContent.includes('1'),'Search reports a match count');search.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true}));check(A.State.sel==='scene'&&$('#search-results').textContent==='1 / 1','Search navigates to the matching node');search.value='nonexistent_word';search.dispatchEvent(new Event('input'));check($('#search-results').textContent==='No matches','Search gives an explicit empty state');search.value='';search.dispatchEvent(new Event('input'));document.activeElement.blur();
  window.dispatchEvent(new KeyboardEvent('keydown',{key:'a',ctrlKey:true,bubbles:true}));check(A.State.selection.length===A.State.order.filter(id=>A.State.nodes[id]._el).length,'Canvas Ctrl+A selects visible nodes');
  search.value='->';search.dispatchEvent(new Event('input'));const matching=A.State.order.filter(id=>A.State.nodes[id].body.includes('->'));search.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',shiftKey:true,bubbles:true}));check(A.State.sel===matching.at(-1),'Previous match starts at the last result');search.value='';search.dispatchEvent(new Event('input'));search.blur();
  A.select('scene');let script=$('#side-body textarea'),originalBody=A.State.nodes.scene.body;script.focus();script.value+='\nCancelled edit';script.dispatchEvent(new Event('input'));A.flushPendingEdit();script.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}));check(A.State.nodes.scene.body===originalBody,'Escape restores a multiline inspector edit');
  category.value='LIST';category.dispatchEvent(new Event('change'));const initialItem=$('.list-initial input');initialItem.checked=true;initialItem.dispatchEvent(new Event('change'));await wait();check(G.declarations().find(v=>v.name==='badges').value.includes('(red)')&&A.compile().story,'List initial-selection control updates valid Ink');category.value='VAR';category.dispatchEvent(new Event('change'));
  const tag=card().querySelector('.condition-tag');check(getComputedStyle(tag).cursor==='default','Informational tags do not advertise dragging');
  check(getComputedStyle(card().querySelector('.prose')).fontFamily===getComputedStyle(card().querySelector('.choice-label')).fontFamily,'Narrative and choice text share typography');
  for(const id of ['b-playclose','b-srcclose','b-errclose'])check($('#'+id).getAttribute('aria-label')?.startsWith('Close'),'Named close control '+id);
  C.selectMany([]);const editTop=[...document.querySelectorAll('.menu-top')].find(e=>e.textContent==='Edit');editTop.click();check(document.querySelector('[data-selection-action="Delete selected nodes"]').disabled,'Delete is disabled without a selection');editTop.click();
  A.load('VAR ready = false\n-> entry\n=== entry ===\n~ ready = true\n-> scene\n=== scene ===\n* {ready} [Ready] -> END\n+ [Wait] -> END');A.select('scene');const testButton=[...document.querySelectorAll('.side-head button')].find(e=>e.textContent==='Test from here');testButton.click();check($('#test-state-dialog').open,'Testing a node explains fresh state before playing');$('#test-state-dialog input').value='true';[...$('#test-state-dialog').querySelectorAll('button')].find(e=>e.textContent==='Play').click();check($('#play-choices').textContent.includes('Ready'),'Test override controls conditional choice availability');check(G.declarations()[0].value==='false','Test overrides do not change authored initial values');$('#b-playclose').click();
  InkblotsRecent.clear();InkblotsRecent.record([{name:'gone.ink',path:'C:/missing/gone.ink'}]);InkblotsRecent.open();check($('#recent-dialog .recent-row').textContent.includes('Locate'),'Recent entry offers locating its replacement');[...$('#recent-dialog').querySelectorAll('button')].find(e=>e.textContent==='Remove').click();check(!InkblotsRecent.entries().length,'A single recent item can be removed');$('#recent-dialog').close();
  A.load(fixture);A.State.layout={'::start':[20,40],scene:[320,40],ending:[660,90]};A.State.view={x:0,y:0,k:.85};A.render();A.applyTransform();A.select('scene');await wait();
  for(const lang of ['ja','zh-CN','pt-BR','en']){InkblotsI18n.setLanguage(lang);check(card().textContent.includes('step inside.'),'Language switch preserves authored response text: '+lang);}
  return true;
}
app.whenReady().then(async()=>{const win=new BrowserWindow({show:false,width:1440,height:1000,webPreferences:{preload:path.join(__dirname,'../preload.js'),sandbox:true,contextIsolation:true,backgroundThrottling:false}});const errors=[];win.webContents.on('console-message',(_e,level,message)=>{if(level===3)errors.push(message);else if(message.startsWith('PASS'))console.log(message);});try{await win.loadFile(path.join(__dirname,'../renderer/index.html'));await win.webContents.executeJavaScript('('+checks.toString()+')()');fs.mkdirSync(output,{recursive:true});for(const theme of ['dark','light']){await win.webContents.executeJavaScript(`document.documentElement.dataset.theme='${theme}'`);await win.webContents.capturePage();await new Promise(r=>setTimeout(r,180));fs.writeFileSync(path.join(output,'design-'+theme+'.png'),(await win.webContents.capturePage()).toPNG());}win.setSize(900,600);await new Promise(r=>setTimeout(r,180));fs.writeFileSync(path.join(output,'design-compact.png'),(await win.webContents.capturePage()).toPNG());if(errors.length)throw Error(errors.join('\n'));console.log('QA captures: '+output);app.exit(0);}catch(error){console.error(error);app.exit(1);}});
