const path = require('node:path');
if (!process.versions.electron) {
  const env = {...process.env}; delete env.ELECTRON_RUN_AS_NODE;
  const result = require('node:child_process').spawnSync(require('electron'), [__filename], {env,stdio:'inherit'});
  if(result.error)throw result.error; process.exit(result.status ?? 1);
}
const {app,BrowserWindow} = require('electron'), fs=require('node:fs');
app.setPath('userData',fs.mkdtempSync(path.join(require('node:os').tmpdir(),'inkblots-canvas-test-')));
require('electron').ipcMain.on('system-languages', e => { e.returnValue=['en-US']; });
app.whenReady().then(async()=>{
  const win=new BrowserWindow({show:false,width:1500,height:1050,titleBarStyle:'hidden',titleBarOverlay:{color:'#161a23',symbolColor:'#e3e7f0',height:48},webPreferences:{preload:path.join(__dirname,'../preload.js'),sandbox:true,contextIsolation:true,backgroundThrottling:false}});
  win.webContents.on('console-message',(_e,level,message)=>{if(level>=2)console.log(message);});
  const out=path.join(__dirname,'../dist/qa');fs.mkdirSync(out,{recursive:true});
  try{
    await win.loadFile(path.join(__dirname,'../renderer/index.html'));
    await win.webContents.insertCSS('*{transition:none!important;animation:none!important}');
    const report=await win.webContents.executeJavaScript(`(async()=>{
      const A=window.Inkblots,C=window.InkblotsCanvas,$=s=>document.querySelector(s),checks=[];
      const check=(ok,msg)=>{if(!ok)throw Error(msg);checks.push(msg);};
      const frame=()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));
      const mouse=(target,type,x,y,extras={})=>target.dispatchEvent(new MouseEvent(type,{clientX:x,clientY:y,button:0,bubbles:true,cancelable:true,...extras}));
      const source='-> arrival\\n=== arrival ===\\n// Establish the mood.\\n// Leave room for a quiet beat.\\n/* A multiline note.\\n=== not_a_knot ===\\n-> not_a_target */\\nWelcome to the station.\\n+ [Continue] -> platform // Main route\\n=== platform ===\\nA distant whistle.\\n-> ending\\n=== ending ===\\nThe train departs.\\n-> END';
      A.openFilesInTabs([{name:'canvas-test.ink',content:source}]);await frame();
      A.State.layout.arrival=[90,130];A.State.layout.platform=[430,130];A.State.layout.ending=[430,520];A.State.layout['::start']=[-350,30];
      A.State.view={x:0,y:0,k:1};A.render();A.applyTransform();await frame();
      check(document.title.includes('Inkblots'),'App renamed');
      check(!A.State.nodes.not_a_knot,'Block comments do not create phantom nodes');
      check(!A.State.nodes.arrival.diverts.some(d=>d.target==='not_a_target'),'Block comments do not create phantom diverts');
      const rect1=A.State.nodes.arrival._el.getBoundingClientRect(),rect2=A.State.nodes.platform._el.getBoundingClientRect();
      mouse($('#canvas'),'mousedown',rect1.left-15,rect1.top-15,{shiftKey:true});
      mouse(window,'mousemove',rect2.right+15,Math.max(rect1.bottom,rect2.bottom)+15,{shiftKey:true});mouse(window,'mouseup',rect2.right+15,Math.max(rect1.bottom,rect2.bottom)+15,{shiftKey:true});
      check(A.State.selection.length===2 && A.State.selection.includes('platform'),'Shift drag box-selects intersecting nodes');
      const original=A.State.layout.arrival.slice(),other=A.State.layout.platform.slice();
      mouse(A.State.nodes.arrival._el.querySelector('.nm'),'mousedown',rect1.left+35,rect1.top+15);mouse(window,'mousemove',rect1.left+85,rect1.top+45);mouse(window,'mouseup',rect1.left+85,rect1.top+45);
      check(A.State.layout.arrival[0]===original[0]+50 && A.State.layout.platform[0]===other[0]+50,'Dragging a selected node moves the selection');
      A.undo();check(A.State.layout.arrival[0]===original[0] && A.State.layout.platform[0]===other[0],'Multi-node movement is undoable');
      C.selectMany(['arrival','platform']);$('#canvas').dispatchEvent(new KeyboardEvent('keydown',{key:'g',ctrlKey:true,bubbles:true,cancelable:true}));check(!$('#scrim').classList.contains('open'),'Ctrl+G creates a zone without a name prompt');
      check(A.State.organizer.zones[0].members.length===2,'Zone contains the selected nodes');
      let zone=A.State.organizer.zones[0],zid=zone.id;const zrect=$('.zone .organizer-title').getBoundingClientRect();
      mouse($('.zone .organizer-title'),'mousedown',zrect.left+5,zrect.top+5);mouse(window,'mousemove',zrect.left+35,zrect.top+35);mouse(window,'mouseup',zrect.left+35,zrect.top+35);
      check(A.State.layout.arrival[0]===original[0]+30,'Zone drag moves its members');
      const handle=$('.zone .organizer-resize').getBoundingClientRect(),oldWidth=zone.w;
      mouse($('.zone .organizer-resize'),'mousedown',handle.left+4,handle.top+4);mouse(window,'mousemove',handle.left+64,handle.top+44);mouse(window,'mouseup',handle.left+64,handle.top+44);
      check(zone.w===oldWidth,'Nonempty zone size follows its members');
      const contains = () => A.State.organizer.zones.every(z => z.members.every(id => {
        const p=A.State.layout[id], el=A.State.nodes[id]._el;
        return z.x<=p[0]-30 && z.y<=p[1]-58 && z.x+z.w>=p[0]+el.offsetWidth+30 && z.y+z.h>=p[1]+el.offsetHeight+30;
      }));
      for (const [dx,dy] of [[-650,0],[0,-450],[1100,0],[0,900]]) {
        C.selectMany(['arrival']); const r=A.State.nodes.arrival._el.getBoundingClientRect();
        mouse(A.State.nodes.arrival._el.querySelector('.nm'),'mousedown',r.left+30,r.top+15);
        mouse(window,'mousemove',r.left+30+dx,r.top+15+dy);mouse(window,'mouseup',r.left+30+dx,r.top+15+dy);
        check(contains(),'Zone contains member after move '+dx+','+dy);
        const moved=A.State.organizer.zones[0], positions=moved.members.map(id=>({p:A.State.layout[id],el:A.State.nodes[id]._el}));
        check(moved.w===Math.max(...positions.map(n=>n.p[0]+n.el.offsetWidth))-Math.min(...positions.map(n=>n.p[0]))+60 && moved.h===Math.max(...positions.map(n=>n.p[1]+n.el.offsetHeight))-Math.min(...positions.map(n=>n.p[1]))+88,'Zone fits tightly after move '+dx+','+dy);
        A.undo();check(contains(),'Zone and member undo together '+dx+','+dy);
      }
      zone=A.State.organizer.zones[0];
      const wide=zone.w;C.selectMany(['platform']);
      let inward=A.State.nodes.platform._el.getBoundingClientRect();
      mouse(A.State.nodes.platform._el.querySelector('.nm'),'mousedown',inward.left+30,inward.top+15);mouse(window,'mousemove',inward.left-90,inward.top+15);mouse(window,'mouseup',inward.left-90,inward.top+15);
      check(A.State.organizer.zones[0].w<wide && contains(),'Moving a member inward contracts its zone');A.undo();
      C.selectMany(['platform']);document.querySelector('.zone button[aria-label="Remove selected nodes from this zone"]').click();
      check(A.State.organizer.zones[0].w===A.State.nodes.arrival._el.offsetWidth+60,'Removing a member contracts the zone');A.undo();
      zone=A.State.organizer.zones[0];
      C.addNote([820,140]);const note=$('.sticky-note textarea');note.value='Check the pacing.\\nKeep this scene quiet.';note.dispatchEvent(new Event('input',{bubbles:true}));
      check(A.State.organizer.notes[0].text.includes('Keep this scene'),'Sticky-note editing updates document state');
      check(A.State.dirty,'Canvas edits mark the document dirty');
      const badge=A.State.nodes.arrival._el.querySelector('.comment-badge');badge.dispatchEvent(new MouseEvent('mouseenter'));
      check(!badge.hasAttribute('title') && $('.comments-title').textContent==='Comments (4)','Comment count appears only in custom header');
      check($('#comments-tooltip').querySelectorAll('p').length===4,'Node comment balloon shows all comments');
      check($('#comments-tooltip').querySelectorAll('hr').length===3,'Comment tooltip separates each comment');
      check(A.State.nodes.arrival._el.querySelectorAll('.comment-badge').length===1,'One comment balloon per node after organization edits');
      const saved=A.serialize(true).text,parsed=A.parse(saved);
      check(parsed.organizer.zones[0].id===zid && parsed.organizer.notes[0].text.includes('quiet'),'Zones and notes serialize into Ink metadata');
      check(!A.serialize(false).text.includes('@inkblots'),'Metadata is excluded from compiled script');
      check(new inkjs.Compiler(saved).Compile(),'Saved Ink including metadata compiles directly');
      A.load(saved,{keepView:true});check(A.State.organizer.zones.length===1 && A.State.organizer.notes.length===1,'Zones and notes restore on reopen');
      A.renameNode('platform','station_platform');check(A.State.organizer.zones[0].members.includes('station_platform'),'Zone membership survives node rename');
      A.undo();check(A.State.organizer.zones[0].members.includes('platform'),'Undo restores group membership');
      const zoneCount=A.State.organizer.zones.length,noteCount=A.State.organizer.notes.length;
      $('#b-source').click();$('#srctext').value+='\\n// source edit';$('#b-srcapply').click();
      check(A.State.organizer.zones.length===zoneCount && A.State.organizer.notes.length===noteCount,'Full-script editing retains canvas organization');
      const tab=A.activeTab;A.newFile();check(A.State.organizer.notes.length===0 && A.State.organizer.zones.length===0,'New tabs have independent organization');A.switchTab(tab);
      check(A.State.organizer.notes.length===noteCount,'Switching tabs restores organization');
      const base=A.State.organizer.notes.length;C.addNote([700,460]);A.undo();check(A.State.organizer.notes.length===base,'Sticky-note creation is undoable');A.redo();check(A.State.organizer.notes.length===base+1,'Sticky-note creation is redoable');A.undo();
      const beforeView=A.State.view.x;$('#minimap').dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true}));check(A.State.view.x!==beforeView,'Minimap keyboard navigation pans canvas');
      const canvasRect=$('#canvas').getBoundingClientRect();
      mouse($('#canvas'),'contextmenu',canvasRect.left+260,canvasRect.top+420,{button:2});
      check(!$('#quick-ink').hidden,'Right-click opens cursor Ink menu');
      const search=$('#quick-ink input');search.value='named section';search.dispatchEvent(new Event('input'));check($('#quick-results').textContent.includes('Knot'),'Cursor menu searches descriptions');
      const worldPoint=A.screenToWorld(canvasRect.left+260,canvasRect.top+420),ids=new Set(A.State.order);
      search.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true,cancelable:true}));
      const added=A.State.order.filter(id=>!ids.has(id));check(added.length===1,'Cursor menu inserts selected snippet');
      check(Math.abs(A.State.layout[added[0]][0]-worldPoint[0])<1,'New snippet is positioned at cursor');
      $('#canvas').dispatchEvent(new KeyboardEvent('keydown',{key:'A',shiftKey:true,bubbles:true,cancelable:true}));check(!$('#quick-ink').hidden,'Shift+A opens Ink menu');
      search.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true,cancelable:true}));check($('#quick-ink').hidden,'Escape dismisses cursor menu');
      check(A.compile().story,'Story with comments and canvas metadata still compiles');
      const existingNodes=A.State.order.length;
      document.querySelector('.zone button[aria-label="Remove zone (keep its nodes)"]').click();
      check(A.State.organizer.zones.length===0 && A.State.order.length===existingNodes,'Removing a zone keeps story nodes');A.undo();
      const n=A.State.organizer.notes[0],nr=$('.sticky-note .organizer-title').getBoundingClientRect(),oldX=n.x;
      mouse($('.sticky-note .organizer-title'),'mousedown',nr.left+4,nr.top+4);mouse(window,'mousemove',nr.left+44,nr.top+24);mouse(window,'mouseup',nr.left+44,nr.top+24);
      check(n.x===oldX+40/A.State.view.k,'Sticky notes can be dragged');A.undo();
      A.State.view={x:0,y:0,k:.8};A.applyTransform();A.render();await frame();
      const r1=A.State.nodes.arrival._el.getBoundingClientRect(),r2=A.State.nodes.platform._el.getBoundingClientRect();
      mouse($('#canvas'),'mousedown',r1.left-5,r1.top-5,{shiftKey:true});mouse(window,'mousemove',r2.right+5,Math.max(r1.bottom,r2.bottom)+5,{shiftKey:true});mouse(window,'mouseup',r2.right+5,Math.max(r1.bottom,r2.bottom)+5,{shiftKey:true});
      check(A.State.selection.includes('arrival') && A.State.selection.includes('platform'),'Box selection stays aligned after zoom');
      C.selectMany(['arrival','platform']);
      A.State.nodes.arrival._el.querySelector('.comment-badge').dispatchEvent(new MouseEvent('mouseenter'));
      check(A.serialize(true).text.includes('// --- Inkblots layout'),'Saved metadata uses current name');
      const legacy=A.parse(A.serialize(true).text.replace('// --- Inkblots layout','// --- inkweave layout'));
      check(legacy.organizer.zones.length && !legacy.nodes['::start']?.body.includes('inkweave layout'),'Legacy layout remains readable');
      A.Tabs.forEach((t,i)=>t.fileName='temporary-'+i+'.ink');
      A.newFile();check(A.State.fileName==='Untitled.ink','First available untitled name is reused');
      A.newFile();check(A.State.fileName==='Untitled-2.ink','Next available untitled name is allocated');
      A.newFile();check(A.State.fileName==='Untitled-3.ink','Open untitled names are unique');
      A.Tabs[A.activeTab-1].fileName='renamed.ink';A.newFile();check(A.State.fileName==='Untitled-2.ink','Lowest available gap is reused');
      const help=[...document.querySelectorAll('[aria-label="Help"] button')].find(b=>b.textContent.includes('Inkblots user guide'));help.click();
      check($('#user-guide').open && $('#user-guide').textContent.includes('Ctrl+G'),'Help opens the quick user guide');
      $('#user-guide button').click();check(!$('#user-guide').open,'User guide closes');
      const tour=window.INK_SNIPPETS.flatMap(g=>g.items).find(it=>it.id==='story-inkblots-tour');A.applySnippet(tour);
      check(A.State.organizer.zones.length===3 && A.State.organizer.notes.length===1,'Showcase loads its zones and sticky note');
      check(A.compile().story,'Showcase compiles in the editor');
      return checks;
    })()`);
    console.log(report.map(x=>'PASS '+x).join('\n'));
    await win.webContents.capturePage();await new Promise(r=>setTimeout(r,150));
    fs.writeFileSync(path.join(out,'canvas-tools.png'),(await win.webContents.capturePage()).toPNG());
    await win.webContents.executeJavaScript(`document.documentElement.setAttribute('data-theme','light');`);
    await win.webContents.capturePage();await new Promise(r=>setTimeout(r,150));
    fs.writeFileSync(path.join(out,'canvas-tools-light.png'),(await win.webContents.capturePage()).toPNG());
    await win.webContents.executeJavaScript('window.showInkblotsGuide()');
    fs.writeFileSync(path.join(out,'user-guide.png'),(await win.webContents.capturePage()).toPNG());
    app.exit(0);
  }catch(e){console.error(e);app.exit(1);}
});
